captcha:
    dot_count: 80
    height: 80
    length: 6
    max_skew: 0.7
    width: 240
cf:
    enabled: true
    bucketname: gvb
    accountid: 5fc9dc2aa7b67503c60fb76703996fa7
    accesskeyid: ad914b48e202396e20149d3c597c8d69
    accesskeysecret: b09e7aa29982b875509b1ea9f1b6264df8b1dc8fde1d9ba19ca8e87e84bfd413
    cdn: ""
cloudflare:
    accesskeyid: ad914b48e202396e20149d3c597c8d69
    accesskeysecret: b09e7aa29982b875509b1ea9f1b6264df8b1dc8fde1d9ba19ca8e87e84bfd413
    accountid: 5fc9dc2aa7b67503c60fb76703996fa7
    bucketname: gvb
    cdn: ""
    enabled: true
email:
    from: 15853696101@163.com
    host: smtp.163.com
    is_ssl: true
    nickname: blog
    port: 465
    secret: RSeD3SbSgaL6uEZa
es:
    is_console_print: true
    password: ""
    url: http://127.0.0.1:9200
    username: ""
gaode:
    enable: false
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
jwt:
    access_token_expiry_time: 2h
    access_token_secret: vvP2K65yDICMJ-mgiksBx456uJ4X8gqVyOG07sm_6ws=
    issuer: go_blog
    refresh_token_expiry_time: 7d
    refresh_token_secret: WL2WjacElZiGCJWivYq-AeJH2P39xAfJQl5Ui2exYGc=
mysql:
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: blog_db
    host: 127.0.0.1
    log_mode: info
    max_idle_conns: 10
    max_open_conns: 100
    password: root
    port: 3306
    username: root
pgsql:
    config: sslmode=disable TimeZone=Asia/Shanghai
    db_name: blog_db
    host: 127.0.0.1
    log_mode: info
    max_idle_conns: 10
    max_open_conns: 100
    password: 0519..
    port: 5432
    username: postgres
qiniu:
    access_key: xxxxxxxxxxxxxxxxxxxxxxxx
    bucket: xxx
    img_path: https://xxx.xxx/
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    use_cdn_domains: true
    use_https: true
    zone: z0
qq:
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    enable: false
    redirect_uri: http://xxx.xxx/xxx
redis:
    address: 127.0.0.1:6379
    db: 0
    password: 123456
system:
    env: release
    host: 0.0.0.0
    oss_type: local
    port: 8080
    router_prefix: api
    sessions_secret: 56Yrue1OdCrt8MFxd_OpisBrSQDNUK2jclqMldwp7Jc=
    use_multipoint: true
upload:
    path: uploads
    size: 20
website:
    address: 山东
    bilibili_url: https://space.bilibili.com/xxx
    created_at: "2025-10-10"
    description: 记录笔记的blog
    email: 1303541051@qq.com
    full_logo: https://pic.hiding.top/pic-node1/main/imagesfull_logo.png
    gitee_url: https://gitee.com/xxx
    github_url: https://github.com/xxx/
    icp_filing: icp备案号
    job: 三天打鱼两天晒网
    logo: https://pic.hiding.top/pic-node1/main/imageslogo16x16.png
    name: avein
    public_security_filing: 公安备案号
    qq_image: ""
    slogan: avein的博客
    slogan_en: avein blog
    title: avein的个人博客
    version: 1.0.0
    wechat_image: ""
zap:
    filename: log/go_blog.log
    is_console_print: true
    level: info
    max_age: 5
    max_backups: 30
    max_size: 200
